### ISSUE TITLE
Could not find package with composer name "flowpack/neos-frontendlogin"

### ISSUE THREAD

**Issue by pozgo** [million12/docker-typo3-neos#2]
When deploying image having this error:
`PHP Fatal error:  Uncaught exception 'TYPO3\Flow\Package\Exception\InvalidPackageStateException' with message 'Could not find package with composer name "flowpack/neos-frontendlogin" in PackageStates configuration.' in /data/www/typo3-app/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Package/PackageManager.php:383`

**Comment by ryzy** [comment]
That's Neos related, not this container related ;-)
It builds it from the master branch... might be fixed by now.
