### ISSUE TITLE
Running multiple Neos on one host

### ISSUE THREAD

**Issue by stillagainst** [million12/docker-typo3-neos#3]
Hello.
I'm impressed how easy it is to get Neos up and running within minutes.
Now I wondered: with the concept of docker, is it possible to run multiple Neos?

What I tried was the two lines described in usage, so I had one db and one neos.

And then:
docker run -d --name=db2 --env="MARIADB_PASS=my-pass" million12/mariadb
docker run -d --name=neos2 -p=8081:80 --link=db2:db --env="T3APP_VHOST_NAMES=neos2 dev.neos2" million12/typo3-neos

I thought that this made me another db and another neos linked to that second db.
I can access the first one from another pc via http://neos:8080 but the second one on http://neos:8081 says:
default vhost # created on Thu Jun 4 06:30:55 UTC 2015

The log of neos2 says:
2015-06-04 06:32:20,937 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-06-04 06:32:20,938 INFO success: nginx-reload entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-06-04 06:32:20,938 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

If I try to access http://neos:8081/neos I get a 404 from nginx an log says:
2015/06/04 06:38:09 [error] 103#0: *7 open() "/data/www/default/neos" failed (2: No such file or directory), client: 10.1.103.47, server: , request: "GET /neos HTTP/1.1", host: "neos:8081"

Am I completely wrong with some basic principles here?

Btw.: my host is a fresh Ubuntu 14.04.1 with just openssh and mc installed and machine name "neos", just a dev machine, no firewall, Docker installed as in the official instructions, the 1st neos is still running perfectly well and accessible from other PC's.

**Comment by ryzy** [comment]
Hey!

If I understood you correctly, things are mixed up here ;-) When you launched 2nd container with the 2nd Neos, you provided `neos2` vhost name. Therefore you can only access it under http://neos2:PORT/. 

You might want to look at the the examples of running two Flow apps (it'd be the same for Neos) here: https://github.com/million12/docker-typo3-flow-neos-abstract/blob/master/circle.yml#L200
The key vars to provide here are T3APP_NAME and T3APP_VHOST_NAMES. I recommend you to read bit more the doc here: https://github.com/million12/docker-typo3-flow-neos-abstract

PS. There's no need to launch 2nd DB container. This Neos container will create separate DB for you (by default, equal to T3APP_NAME).

Hope it helps, let me know if there's still sth unclear ;)

**Comment by stillagainst** [comment]
Hey.
Thanks a lot so far.
Cool I didn't knew that it creates separate DB, but makes sense.
Nice example, I'll try that out including the T3APP_NAME that I missed in the 1st place.

**Comment by ryzy** [comment]
Super ;-)
